/*
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RpgleAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/sitemule/rpglanguage/parser/antlr/internal/InternalRpgleParser.tokens");
	}
}
