/**
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage.rpgle.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.sitemule.rpglanguage.rpgle.BoolExpr;
import org.sitemule.rpglanguage.rpgle.Code;
import org.sitemule.rpglanguage.rpgle.RpglePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Boolean</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.sitemule.rpglanguage.rpgle.impl.BooleanImpl#getWhencode <em>Whencode</em>}</li>
 *   <li>{@link org.sitemule.rpglanguage.rpgle.impl.BooleanImpl#getBoolexprs <em>Boolexprs</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BooleanImpl extends IfImpl implements org.sitemule.rpglanguage.rpgle.Boolean
{
  /**
   * The cached value of the '{@link #getWhencode() <em>Whencode</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWhencode()
   * @generated
   * @ordered
   */
  protected EList<Code> whencode;

  /**
   * The cached value of the '{@link #getBoolexprs() <em>Boolexprs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBoolexprs()
   * @generated
   * @ordered
   */
  protected EList<BoolExpr> boolexprs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BooleanImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RpglePackage.Literals.BOOLEAN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Code> getWhencode()
  {
    if (whencode == null)
    {
      whencode = new EObjectContainmentEList<Code>(Code.class, this, RpglePackage.BOOLEAN__WHENCODE);
    }
    return whencode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<BoolExpr> getBoolexprs()
  {
    if (boolexprs == null)
    {
      boolexprs = new EObjectContainmentEList<BoolExpr>(BoolExpr.class, this, RpglePackage.BOOLEAN__BOOLEXPRS);
    }
    return boolexprs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RpglePackage.BOOLEAN__WHENCODE:
        return ((InternalEList<?>)getWhencode()).basicRemove(otherEnd, msgs);
      case RpglePackage.BOOLEAN__BOOLEXPRS:
        return ((InternalEList<?>)getBoolexprs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RpglePackage.BOOLEAN__WHENCODE:
        return getWhencode();
      case RpglePackage.BOOLEAN__BOOLEXPRS:
        return getBoolexprs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RpglePackage.BOOLEAN__WHENCODE:
        getWhencode().clear();
        getWhencode().addAll((Collection<? extends Code>)newValue);
        return;
      case RpglePackage.BOOLEAN__BOOLEXPRS:
        getBoolexprs().clear();
        getBoolexprs().addAll((Collection<? extends BoolExpr>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RpglePackage.BOOLEAN__WHENCODE:
        getWhencode().clear();
        return;
      case RpglePackage.BOOLEAN__BOOLEXPRS:
        getBoolexprs().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RpglePackage.BOOLEAN__WHENCODE:
        return whencode != null && !whencode.isEmpty();
      case RpglePackage.BOOLEAN__BOOLEXPRS:
        return boolexprs != null && !boolexprs.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //BooleanImpl
