/**
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage.rpgle.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.sitemule.rpglanguage.rpgle.Code;
import org.sitemule.rpglanguage.rpgle.Dow;
import org.sitemule.rpglanguage.rpgle.RpglePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dow</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.sitemule.rpglanguage.rpgle.impl.DowImpl#getDow <em>Dow</em>}</li>
 *   <li>{@link org.sitemule.rpglanguage.rpgle.impl.DowImpl#getCode <em>Code</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DowImpl extends StmtImpl implements Dow
{
  /**
   * The cached value of the '{@link #getDow() <em>Dow</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDow()
   * @generated
   * @ordered
   */
  protected org.sitemule.rpglanguage.rpgle.Boolean dow;

  /**
   * The cached value of the '{@link #getCode() <em>Code</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCode()
   * @generated
   * @ordered
   */
  protected EList<Code> code;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DowImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RpglePackage.Literals.DOW;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public org.sitemule.rpglanguage.rpgle.Boolean getDow()
  {
    return dow;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDow(org.sitemule.rpglanguage.rpgle.Boolean newDow, NotificationChain msgs)
  {
    org.sitemule.rpglanguage.rpgle.Boolean oldDow = dow;
    dow = newDow;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RpglePackage.DOW__DOW, oldDow, newDow);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDow(org.sitemule.rpglanguage.rpgle.Boolean newDow)
  {
    if (newDow != dow)
    {
      NotificationChain msgs = null;
      if (dow != null)
        msgs = ((InternalEObject)dow).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RpglePackage.DOW__DOW, null, msgs);
      if (newDow != null)
        msgs = ((InternalEObject)newDow).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RpglePackage.DOW__DOW, null, msgs);
      msgs = basicSetDow(newDow, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RpglePackage.DOW__DOW, newDow, newDow));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Code> getCode()
  {
    if (code == null)
    {
      code = new EObjectContainmentEList<Code>(Code.class, this, RpglePackage.DOW__CODE);
    }
    return code;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RpglePackage.DOW__DOW:
        return basicSetDow(null, msgs);
      case RpglePackage.DOW__CODE:
        return ((InternalEList<?>)getCode()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RpglePackage.DOW__DOW:
        return getDow();
      case RpglePackage.DOW__CODE:
        return getCode();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RpglePackage.DOW__DOW:
        setDow((org.sitemule.rpglanguage.rpgle.Boolean)newValue);
        return;
      case RpglePackage.DOW__CODE:
        getCode().clear();
        getCode().addAll((Collection<? extends Code>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RpglePackage.DOW__DOW:
        setDow((org.sitemule.rpglanguage.rpgle.Boolean)null);
        return;
      case RpglePackage.DOW__CODE:
        getCode().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RpglePackage.DOW__DOW:
        return dow != null;
      case RpglePackage.DOW__CODE:
        return code != null && !code.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //DowImpl
