/**
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage.rpgle.impl;

import org.eclipse.emf.ecore.EClass;

import org.sitemule.rpglanguage.rpgle.RpglePackage;
import org.sitemule.rpglanguage.rpgle.Setgt;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Setgt</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SetgtImpl extends FileioImpl implements Setgt
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SetgtImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RpglePackage.Literals.SETGT;
  }

} //SetgtImpl
