/**
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage.rpgle.impl;

import org.eclipse.emf.ecore.EClass;

import org.sitemule.rpglanguage.rpgle.RpglePackage;
import org.sitemule.rpglanguage.rpgle.Setll;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Setll</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SetllImpl extends FileioImpl implements Setll
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SetllImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RpglePackage.Literals.SETLL;
  }

} //SetllImpl
