/*
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RpgleStandaloneSetup extends RpgleStandaloneSetupGenerated {

	def static void doSetup() {
		new RpgleStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
