/*
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RpgleRuntimeModule extends AbstractRpgleRuntimeModule {
}
