/*
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRpgleScopeProvider extends DelegatingScopeProvider {
}
