/**
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage.rpgle;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sitemule.rpglanguage.rpgle.Boolean#getWhencode <em>Whencode</em>}</li>
 *   <li>{@link org.sitemule.rpglanguage.rpgle.Boolean#getBoolexprs <em>Boolexprs</em>}</li>
 * </ul>
 *
 * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getBoolean()
 * @model
 * @generated
 */
public interface Boolean extends If, Elseif, When
{
  /**
   * Returns the value of the '<em><b>Whencode</b></em>' containment reference list.
   * The list contents are of type {@link org.sitemule.rpglanguage.rpgle.Code}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Whencode</em>' containment reference list.
   * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getBoolean_Whencode()
   * @model containment="true"
   * @generated
   */
  EList<Code> getWhencode();

  /**
   * Returns the value of the '<em><b>Boolexprs</b></em>' containment reference list.
   * The list contents are of type {@link org.sitemule.rpglanguage.rpgle.BoolExpr}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Boolexprs</em>' containment reference list.
   * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getBoolean_Boolexprs()
   * @model containment="true"
   * @generated
   */
  EList<BoolExpr> getBoolexprs();

} // Boolean
