/**
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage.rpgle;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bool Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getBoolExpr()
 * @model
 * @generated
 */
public interface BoolExpr extends EObject
{
} // BoolExpr
