/**
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage.rpgle;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chain</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getChain()
 * @model
 * @generated
 */
public interface Chain extends Fileio
{
} // Chain
