/**
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage.rpgle;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ctrlopt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sitemule.rpglanguage.rpgle.Ctrlopt#getOpt <em>Opt</em>}</li>
 * </ul>
 *
 * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getCtrlopt()
 * @model
 * @generated
 */
public interface Ctrlopt extends Components
{
  /**
   * Returns the value of the '<em><b>Opt</b></em>' containment reference list.
   * The list contents are of type {@link org.sitemule.rpglanguage.rpgle.Opt}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Opt</em>' containment reference list.
   * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getCtrlopt_Opt()
   * @model containment="true"
   * @generated
   */
  EList<Opt> getOpt();

} // Ctrlopt
