/**
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage.rpgle;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Datatype</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sitemule.rpglanguage.rpgle.Datatype#getLen <em>Len</em>}</li>
 * </ul>
 *
 * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getDatatype()
 * @model
 * @generated
 */
public interface Datatype extends EObject
{
  /**
   * Returns the value of the '<em><b>Len</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Len</em>' attribute.
   * @see #setLen(String)
   * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getDatatype_Len()
   * @model
   * @generated
   */
  String getLen();

  /**
   * Sets the value of the '{@link org.sitemule.rpglanguage.rpgle.Datatype#getLen <em>Len</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Len</em>' attribute.
   * @see #getLen()
   * @generated
   */
  void setLen(String value);

} // Datatype
