/**
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage.rpgle;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Elseif</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getElseif()
 * @model
 * @generated
 */
public interface Elseif extends EObject
{
} // Elseif
