/**
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage.rpgle;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Eof</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getEof()
 * @model
 * @generated
 */
public interface Eof extends Fileio, Bif
{
} // Eof
