/**
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage.rpgle;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sitemule.rpglanguage.rpgle.Expression#getIntval <em>Intval</em>}</li>
 *   <li>{@link org.sitemule.rpglanguage.rpgle.Expression#getStrval <em>Strval</em>}</li>
 *   <li>{@link org.sitemule.rpglanguage.rpgle.Expression#getVar <em>Var</em>}</li>
 *   <li>{@link org.sitemule.rpglanguage.rpgle.Expression#getProcval <em>Procval</em>}</li>
 *   <li>{@link org.sitemule.rpglanguage.rpgle.Expression#getParmlist <em>Parmlist</em>}</li>
 * </ul>
 *
 * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Intval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Intval</em>' attribute.
   * @see #setIntval(int)
   * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getExpression_Intval()
   * @model
   * @generated
   */
  int getIntval();

  /**
   * Sets the value of the '{@link org.sitemule.rpglanguage.rpgle.Expression#getIntval <em>Intval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Intval</em>' attribute.
   * @see #getIntval()
   * @generated
   */
  void setIntval(int value);

  /**
   * Returns the value of the '<em><b>Strval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Strval</em>' attribute.
   * @see #setStrval(String)
   * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getExpression_Strval()
   * @model
   * @generated
   */
  String getStrval();

  /**
   * Sets the value of the '{@link org.sitemule.rpglanguage.rpgle.Expression#getStrval <em>Strval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Strval</em>' attribute.
   * @see #getStrval()
   * @generated
   */
  void setStrval(String value);

  /**
   * Returns the value of the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' reference.
   * @see #setVar(Dcls)
   * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getExpression_Var()
   * @model
   * @generated
   */
  Dcls getVar();

  /**
   * Sets the value of the '{@link org.sitemule.rpglanguage.rpgle.Expression#getVar <em>Var</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' reference.
   * @see #getVar()
   * @generated
   */
  void setVar(Dcls value);

  /**
   * Returns the value of the '<em><b>Procval</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Procval</em>' reference.
   * @see #setProcval(Dclproc)
   * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getExpression_Procval()
   * @model
   * @generated
   */
  Dclproc getProcval();

  /**
   * Sets the value of the '{@link org.sitemule.rpglanguage.rpgle.Expression#getProcval <em>Procval</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Procval</em>' reference.
   * @see #getProcval()
   * @generated
   */
  void setProcval(Dclproc value);

  /**
   * Returns the value of the '<em><b>Parmlist</b></em>' containment reference list.
   * The list contents are of type {@link org.sitemule.rpglanguage.rpgle.Parmlist}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parmlist</em>' containment reference list.
   * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getExpression_Parmlist()
   * @model containment="true"
   * @generated
   */
  EList<Parmlist> getParmlist();

} // Expression
