/**
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage.rpgle;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exsr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sitemule.rpglanguage.rpgle.Exsr#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getExsr()
 * @model
 * @generated
 */
public interface Exsr extends Stmt
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(Subrutine)
   * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getExsr_Name()
   * @model
   * @generated
   */
  Subrutine getName();

  /**
   * Sets the value of the '{@link org.sitemule.rpglanguage.rpgle.Exsr#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(Subrutine value);

} // Exsr
