/**
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage.rpgle;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Other</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sitemule.rpglanguage.rpgle.Other#getOthercode <em>Othercode</em>}</li>
 * </ul>
 *
 * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getOther()
 * @model
 * @generated
 */
public interface Other extends EObject
{
  /**
   * Returns the value of the '<em><b>Othercode</b></em>' containment reference list.
   * The list contents are of type {@link org.sitemule.rpglanguage.rpgle.Code}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Othercode</em>' containment reference list.
   * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getOther_Othercode()
   * @model containment="true"
   * @generated
   */
  EList<Code> getOthercode();

} // Other
