/**
 * generated by Xtext 2.19.0
 */
package org.sitemule.rpglanguage.rpgle;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parm1</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sitemule.rpglanguage.rpgle.Parm1#getParms <em>Parms</em>}</li>
 *   <li>{@link org.sitemule.rpglanguage.rpgle.Parm1#getParm <em>Parm</em>}</li>
 * </ul>
 *
 * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getParm1()
 * @model
 * @generated
 */
public interface Parm1 extends Parmlist, Parm2
{
  /**
   * Returns the value of the '<em><b>Parms</b></em>' containment reference list.
   * The list contents are of type {@link org.sitemule.rpglanguage.rpgle.Parm2}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parms</em>' containment reference list.
   * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getParm1_Parms()
   * @model containment="true"
   * @generated
   */
  EList<Parm2> getParms();

  /**
   * Returns the value of the '<em><b>Parm</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parm</em>' containment reference.
   * @see #setParm(Expression)
   * @see org.sitemule.rpglanguage.rpgle.RpglePackage#getParm1_Parm()
   * @model containment="true"
   * @generated
   */
  Expression getParm();

  /**
   * Sets the value of the '{@link org.sitemule.rpglanguage.rpgle.Parm1#getParm <em>Parm</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parm</em>' containment reference.
   * @see #getParm()
   * @generated
   */
  void setParm(Expression value);

} // Parm1
